### PR TITLE
fixed typos in chapters 1 to 5

### PR DESCRIPTION
**Pull request by jpmarindiaz**
Some typos fixed.

And some notes for additional review on your end:

**Chapter 2**
broken ref @secure

**Chapter 4**

Weird characters in file structure
```
[01;34mgolex[0m
├── DESCRIPTION
├── NAMESPACE
├── [01;34mR[0m
│   ├── [32mapp_config.R[0m
│   ├── [32mapp_server.R[0m
```
...
readon: a {golem} app IS a package. ---> include link?

Additional line to check (I know what you mean but these lines may be unclear for others).
...
This is not to be done with a {golem}-based application: you are leveraging the package infrastructure so that everything inside the R/ folder is made available internally, without having to source() scripts.
...
Just as with their server counterparts, the UI side of these elements are the one from the bottom of the file you are creating with golem::add_module().

### CODE REVIEW

**Comment by ColinFay** [comment]
Thanks you, very much appreciated!!

Would you be okay commenting this below?

> "I assign the copyright of this contribution to Colin Fay, Vincent Guyader, Cervan Girard and Sébastien Rochette"

Once merged, I'll add your name to the Acknowledgments section in the intro 💪

**Comment by ColinFay** [comment]
The weird characters you're referring to seems to be an issue with the GitHub action build :/ 
See #147

**Comment by jpmarindiaz** [comment]
I assign the copyright of this contribution to Colin Fay, Vincent Guyader, Cervan Girard and Sébastien Rochette

💪

**Comment by ColinFay** [comment]
thank you!

**Pull request merged**
